### ISSUE TITLE
Linux Input

### ISSUE THREAD

**Issue by concubidated** [kategray/technomotion-io#4]
The Linux Event handler does not work with the IO boards due to the terrible check it does to see if something is a joystick.

It checks for X axis, throttle and wheel. 
https://github.com/stepmania/stepmania/blob/5_1-new/src/arch/InputHandler/InputHandler_Linux_Event.cpp#L146

To get these to work in SM you need to add the LinuxJoystick driver to your input devices.

In Preferences.ini
```InputDevices=LinuxEvent,X11,LinuxJoystick```

Figured this info could help someone else.

**Comment by kategray** [comment]
Just came across this.  Eww.

I'll add a dummy throttle and wheel if that's necessary to get this working.

**Comment by kategray** [comment]
@concubidated Is the HID input driver not supported?

**Comment by kategray** [comment]
Closing this as I never got a response.
