### ISSUE TITLE
No input on boot.

### ISSUE THREAD

**Issue by MrAshDarksideTM** [kategray/technomotion-io#5]
Whenever I boot the system with a Ghett.io plugged in, it is seen in Windows game controllers, but no inputs work.  If I physically disconnect and reconnect the USB cable, they work fine.  Is there anyway to address that as I'd like to do a fairly clean, cable hidden install.  Problem is duplicated in Windows 7, Windows 10, as well as Ubuntu.  I've tried using Devcon to refresh the USB ports via software but no luck there.  Thanks!

**Comment by ianklatzco** [comment]
Are you using Stepmania?

**Comment by MrAshDarksideTM** [comment]
Yes.

**Comment by ianklatzco** [comment]
Simply Love has an IO test screen that lists recognized devices. Does the Ghett-io show up there:
* right after you boot, before you unplug/replug it?
* after you unplug/replug it?

**Comment by MrAshDarksideTM** [comment]
Yeah, they both show up as J1 and J2.  No response in stepmania, but unplugging them and plugging them in they work fine.

**Comment by kategray** [comment]
I will have time to look at this next week.  I likely can't get the root issue fixed without being able to reproduce it, but I have a version of the firmware I'm working on that auto-resets when USB breaks. 
 Depending on what's wrong, that may or may not fix the issue.

@MrAshDarksideTM Can you try doing a firmware update using the utility?

https://github.com/kategray/technomotion-io/releases/download/2.0/Firmware.Upgrader.zip

The firmware updater does a reset as part of it's normal operation.  I'm curious if booting and updating, running through the bootloader than getting reset fixes the issue.  If so, I can also add a reset command to the firmware at the very least.

**Comment by MrAshDarksideTM** [comment]
Updated firmware on both of them and they became immediately responsive right after, so it seems that reset does the trick for sure.  Goes back to being unresponsive after a restart of the PC though, but definitely promising. :)

**Comment by kategray** [comment]
Does it do it on a full power off cold boot?

**Comment by MrAshDarksideTM** [comment]
Yeah, same results weather restart, or cold boot.

**Comment by kategray** [comment]
@MrAshDarksideTM can you try the v3.0 beta release, please?

**Comment by MrAshDarksideTM** [comment]
For sure, I'll fire it up after work today.

**Comment by MrAshDarksideTM** [comment]
So far it seems to have fixed the problem!

**Comment by kategray** [comment]
Closing this as fixed unless you have further problems.
